import { StyleSheet, type TextStyle, type ViewStyle } from 'react-native'
import type { ThemeColors } from '../theme/tokens'

export function makeUiStyles(c: ThemeColors) {
  return StyleSheet.create({
    panel: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 18,
    } as ViewStyle,
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    } as ViewStyle,
    wrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    } as ViewStyle,
    subtabs: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      padding: 4,
      borderRadius: 14,
      backgroundColor: c.fill2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hair,
    } as ViewStyle,
    tabBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      minHeight: 44,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    } as ViewStyle,
    tabBtnOn: {
      backgroundColor: c.thumb2,
    } as ViewStyle,
    tabText: {
      color: c.text2,
      fontSize: 14,
      fontWeight: '600',
    } as TextStyle,
    tabTextOn: {
      color: c.onThumb,
    } as TextStyle,
    ghostBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      minHeight: 44,
      borderRadius: 14,
      backgroundColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
    } as ViewStyle,
    ghostText: {
      color: c.accentFg,
      fontSize: 14,
      fontWeight: '600',
    } as TextStyle,
    primaryBtn: {
      paddingHorizontal: 16,
      paddingVertical: 11,
      minHeight: 44,
      borderRadius: 14,
      backgroundColor: c.accent,
      alignItems: 'center',
      justifyContent: 'center',
    } as ViewStyle,
    primaryText: {
      color: c.onAccent,
      fontSize: 14,
      fontWeight: '700',
    } as TextStyle,
    dangerBtn: {
      paddingHorizontal: 16,
      paddingVertical: 11,
      minHeight: 44,
      borderRadius: 14,
      backgroundColor: c.tintRedBg,
      borderWidth: 1,
      borderColor: c.tintRedBd,
      alignItems: 'center',
      justifyContent: 'center',
    } as ViewStyle,
    dangerText: {
      color: c.redFg,
      fontSize: 14,
      fontWeight: '700',
    } as TextStyle,
    btn: {
      paddingHorizontal: 16,
      paddingVertical: 11,
      minHeight: 44,
      borderRadius: 14,
      backgroundColor: c.glass2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hair,
      alignItems: 'center',
      justifyContent: 'center',
    } as ViewStyle,
    btnText: {
      color: c.text,
      fontSize: 14,
      fontWeight: '600',
    } as TextStyle,
    btnDisabled: {
      opacity: 0.35,
    } as ViewStyle,
    sectionTitle: {
      color: c.text2,
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      marginTop: 6,
    } as TextStyle,
    hint: {
      color: c.text3,
      fontSize: 12,
      fontWeight: '400',
    } as TextStyle,
    label: {
      color: c.text2,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 8,
      marginBottom: 6,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    } as TextStyle,
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      minHeight: 44,
      borderRadius: 14,
      backgroundColor: c.glass2,
      borderWidth: 1.5,
      borderColor: 'transparent',
    } as ViewStyle,
    chipOn: {
      backgroundColor: c.accentTint,
      borderColor: c.accent,
    } as ViewStyle,
    chipText: {
      color: c.text,
      fontSize: 14,
      fontWeight: '600',
    } as TextStyle,
    empty: {
      color: c.text2,
      fontSize: 13,
      paddingVertical: 16,
      paddingHorizontal: 12,
      textAlign: 'center',
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: c.hair,
      borderRadius: 22,
    } as TextStyle,
    spacer: {
      flex: 1,
    } as ViewStyle,
  })
}
